
const FIELD_VACANCY_HELPER_TEXT_DEFAULT = 'Vacancy position';
const FIELD_VACANCY_HELPER_TEXT_DEFAULT_LENGTH_ERROR = 'Vacancy position length must be greater than 10 symbols';

export {
  FIELD_VACANCY_HELPER_TEXT_DEFAULT,
  FIELD_VACANCY_HELPER_TEXT_DEFAULT_LENGTH_ERROR
};